Update 2_usecase.yml

diff --git a/.github/workflows/2_usecase.yml b/.github/workflows/2_usecase.yml
--- a/.github/workflows/2_usecase.yml
+++ b/.github/workflows/2_usecase.yml
@@ -37,4 +37,29 @@ jobs:
             exit 1
           fi
 
+          if ! cat "${page}" | grep -iq "импорт"; then 
+            echo "::error::Предварительная проверка не пройдена - не найден сценарий, связанный с импортом данных в систему" 
+            exit 1
+          fi
+
+          if ! cat "${page}" | grep -iq "экспорт"; then 
+            echo "::error::Предварительная проверка не пройдена - не найден сценарий, связанный с экспортом данных в систему" 
+            exit 1
+          fi
+
+          if ! cat "${page}" | grep -iq "статистик"; then 
+            echo "::error::Предварительная проверка не пройдена - не найден сценарий, связанный с подсчетом статистики в системе" 
+            exit 1
+          fi
+
+          if ! cat "${page}" | grep -iq "статистик"; then 
+            echo "::error::Предварительная проверка не пройдена - не найдены изображения макета из репозитория. Вставьте их через \![Название картинки](полная ссылка вида https://github.com/moevm/nosql2h23-ecology/assets/34864759/8f850ef1-fc3d-4adb-a7aa-81598cc7794c) . Если вы храните изображение макета где-то ВНЕ репозитория, то, пожалуйста, разместите файлы в репо - иначе потом очень сложно собирать материалы вашей проекта." 
+            exit 1
+          fi
+
+          if cat "${page}" | grep 'https\:\/\/' | grep -qv github; then 
+            echo "::error::Предварительная проверка не пройдена - найдены ссылки на сторонние сервисы. Если части вашего макета и сценария размещены где-то еще, то, пожалуйста 1) соберите их на вики 2) если у вас сложный макет с figma и тд - положите в репо качественную схему в виде графа. Иначе потом очень сложно собирать материалы вашего проекта." 
+            exit 1
+          fi          
+
           echo "::notice::Предварительная проверка пройдена - вики-страница найдена, нужные заголовки присутствуют"
