fixes after testing 1

diff --git a/.github/workflows/3_data_model.yml b/.github/workflows/3_data_model.yml
--- a/.github/workflows/3_data_model.yml
+++ b/.github/workflows/3_data_model.yml
@@ -11,7 +11,7 @@ jobs:
     name: "Проверка наличия вики-страницы \"Модель данных\" и разделов \"Нереляционная модель\",  \"Реляционная модель\", \"Сравнение моделей\", \"Вывод\" в ней"
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
         name: Check wiki
         with:
           repository: ${{github.repository}}.wiki
@@ -24,6 +24,7 @@ jobs:
           conclusion="Вывод"
           query_examples="Примеры запросов"
           data_examples="Примеры данных"
+          redundancy="Избыточность данных"
            
           if ! [[ -f "${page}" ]]; then 
             echo "::error::Предварительная проверка не пройдена - не найдена вики-страница \"Модель данных\""
@@ -41,6 +42,11 @@ jobs:
             exit 1
           fi
 
+          image_count=`cat "${page}" | grep '](https\:\/\/github.com\/moevm\/[^/]\+\/assets[^\)]\+)' | wc -l`
+          if [[ ${image_count} -lt 2  ]]; then
+            echo "::error::Предварительная проверка не пройдена - не найдены изображения для схем моделей данных. Для реляционной и нереляционной модели необходимо разместить изображения схем моделей данных.  Вставьте их через \![Название картинки](полная ссылка вида https://github.com/moevm/ВАШ РЕПО/assets/34864759/8f850ef1-fc3d-4adb-a7aa-81598cc7794c) . Если вы храните изображение макета где-то ВНЕ репозитория, то, пожалуйста, разместите файлы в репо - иначе потом очень сложно собирать материалы вашей проекта. "
+            exit 1
+          fi
 
           query_examples_count=`cat "${page}" | grep  "${query_examples}" | wc -l`
           if [[  "${query_examples_count}" != "2" ]]; then 
@@ -51,6 +57,12 @@ jobs:
           data_examples_count=`cat "${page}" | grep  "${data_examples}" | wc -l`
           if [[  "${data_examples_count}" != "2" ]]; then 
             echo "::error::Предварительная проверка не пройдена - не найдены заголовоки ${data_examples} (соответствующие подразделы должны быть в разделах с нереляционной и реляционной моделями)."
+            exit 1
+          fi
+
+          redundancy_count=`cat "${page}" | grep  "${redundancy}" | wc -l`
+          if [[  "${redundancy_count}" != "2" ]]; then 
+            echo "::error::Предварительная проверка не пройдена - не найдены заголовоки ${redundancy} (соответствующие подразделы должны быть в разделах с нереляционной и реляционной моделями)."
             exit 1
           fi
 
